# Generated by Django 5.2.11 on 2026-03-02 11:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals_v2', '0002_add_pipeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealStageHistoryV2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_stage', models.CharField(blank=True, max_length=100, null=True)),
                ('to_stage', models.CharField(max_length=100)),
                ('changed_by', models.UUIDField(blank=True, null=True)),
                ('time_in_stage_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='deals_v2.dealv2')),
            ],
            options={
                'verbose_name': 'Deal Stage History V2',
                'verbose_name_plural': 'Deal Stage Histories V2',
                'db_table': 'crm_deal_stage_history_v2',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['deal', 'created_at'], name='deal_stage_hist_v2_idx')],
            },
        ),
    ]
