# Generated by Django 5.2.11 on 2026-03-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals_v2', '0003_add_stage_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealv2',
            name='pipeline_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Pipeline this deal belongs to (UUID referencing PipelineV2)', null=True),
        ),
        migrations.AlterField(
            model_name='dealv2',
            name='stage',
            field=models.CharField(db_index=True, default='qualification', max_length=50),
        ),
    ]
