# Generated by Django 5.2.10 on 2026-03-03 06:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagV2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#6B7280', max_length=7)),
                ('entity_type', models.CharField(choices=[('contact', 'Contact'), ('company', 'Company'), ('deal', 'Deal'), ('lead', 'Lead'), ('all', 'All')], default='all', max_length=20)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crm_tags_v2',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['org_id', 'entity_type'], name='tags_v2_org_type_idx')],
                'constraints': [models.UniqueConstraint(fields=('org_id', 'name', 'entity_type'), name='unique_tag_v2_per_org')],
            },
        ),
        migrations.CreateModel(
            name='EntityTagV2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=20)),
                ('entity_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tags_v2.tagv2')),
            ],
            options={
                'db_table': 'crm_entity_tags_v2',
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='entity_tags_v2_entity_idx'), models.Index(fields=['tag'], name='entity_tags_v2_tag_idx')],
                'constraints': [models.UniqueConstraint(fields=('tag', 'entity_type', 'entity_id'), name='unique_entity_tag_v2')],
            },
        ),
    ]
