# Generated by Django 5.2.11 on 2026-03-02 11:13

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityV2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('owner_id', models.UUIDField(db_index=True)),
                ('activity_type', models.CharField(choices=[('task', 'Task'), ('note', 'Note'), ('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting')], db_index=True, max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1440)])),
                ('call_direction', models.CharField(blank=True, choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10, null=True)),
                ('call_outcome', models.CharField(blank=True, choices=[('answered', 'Answered'), ('voicemail', 'Voicemail'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('failed', 'Failed')], max_length=50, null=True)),
                ('email_direction', models.CharField(blank=True, choices=[('sent', 'Sent'), ('received', 'Received')], max_length=10, null=True)),
                ('email_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('deal_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('lead_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('assigned_to_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('reminder_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Activity V2',
                'verbose_name_plural': 'Activities V2',
                'db_table': 'crm_activities_v2',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['org_id', 'activity_type'], name='activities_v2_type_idx'), models.Index(fields=['org_id', 'status'], name='activities_v2_status_idx'), models.Index(fields=['org_id', 'owner_id'], name='activities_v2_owner_idx'), models.Index(fields=['org_id', 'assigned_to_id'], name='activities_v2_assigned_idx'), models.Index(fields=['org_id', 'due_date'], name='activities_v2_due_idx'), models.Index(fields=['org_id', 'deleted_at'], name='activities_v2_deleted_idx')],
            },
        ),
    ]
