# Generated by Django 5.2.11 on 2026-02-13 10:15

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='deleted_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='deleted_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='deleted_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='company',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='company_name_search_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=django.contrib.postgres.indexes.GinIndex(fields=['first_name', 'last_name'], name='contact_name_search_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=django.contrib.postgres.indexes.GinIndex(fields=['email'], name='contact_email_search_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='deal_name_search_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=django.contrib.postgres.indexes.GinIndex(fields=['first_name', 'last_name'], name='lead_name_search_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=django.contrib.postgres.indexes.GinIndex(fields=['email'], name='lead_email_search_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=django.contrib.postgres.indexes.GinIndex(fields=['company_name'], name='lead_company_search_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='deal_value_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(('probability__isnull', True), models.Q(('probability__gte', 0), ('probability__lte', 100)), _connector='OR'), name='deal_probability_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='pipeline',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('org_id',), name='unique_default_pipeline_per_org'),
        ),
        migrations.AddConstraint(
            model_name='pipelinestage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_won', True)), fields=('pipeline',), name='unique_won_stage_per_pipeline'),
        ),
        migrations.AddConstraint(
            model_name='pipelinestage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_lost', True)), fields=('pipeline',), name='unique_lost_stage_per_pipeline'),
        ),
        migrations.AddConstraint(
            model_name='pipelinestage',
            constraint=models.CheckConstraint(condition=models.Q(('is_lost', True), ('is_won', True), _negated=True), name='stage_not_both_won_and_lost'),
        ),
    ]
