# Generated by Django 5.2.11 on 2026-02-16 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_contact_deleted_at_contact_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='call_direction',
            field=models.CharField(blank=True, choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='call_outcome',
            field=models.CharField(blank=True, choices=[('answered', 'Answered'), ('voicemail', 'Voicemail'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('failed', 'Failed')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1440)]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='email_direction',
            field=models.CharField(blank=True, choices=[('sent', 'Sent'), ('received', 'Received')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
