# Generated by Django 5.2.11 on 2026-02-26 11:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadV2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('owner_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('unqualified', 'Unqualified'), ('converted', 'Converted')], db_index=True, default='new', max_length=20)),
                ('entity_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('converted_contact_id', models.UUIDField(blank=True, null=True)),
                ('converted_company_id', models.UUIDField(blank=True, null=True)),
                ('converted_deal_id', models.UUIDField(blank=True, null=True)),
                ('converted_by', models.UUIDField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lead V2 (Dynamic)',
                'verbose_name_plural': 'Leads V2 (Dynamic)',
                'db_table': 'crm_leads_v2',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['org_id', 'status'], name='crm_leads_v_org_id_56d69c_idx'), models.Index(fields=['org_id', 'owner_id'], name='crm_leads_v_org_id_ab88ce_idx'), models.Index(fields=['org_id', 'created_at'], name='crm_leads_v_org_id_6fec79_idx'), models.Index(fields=['org_id', 'deleted_at'], name='crm_leads_v_org_id_314041_idx')],
            },
        ),
    ]
