# Generated by Django 5.2.11 on 2026-02-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_v2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadv2',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lead V2 (Hybrid)', 'verbose_name_plural': 'Leads V2 (Hybrid)'},
        ),
        migrations.RemoveIndex(
            model_name='leadv2',
            name='crm_leads_v_org_id_56d69c_idx',
        ),
        migrations.RenameIndex(
            model_name='leadv2',
            new_name='leads_v2_recent_idx',
            old_name='crm_leads_v_org_id_6fec79_idx',
        ),
        migrations.AddField(
            model_name='leadv2',
            name='assigned_to_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Currently assigned sales rep (UUID)', null=True),
        ),
        migrations.AddField(
            model_name='leadv2',
            name='company_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Associated company (UUID)', null=True),
        ),
        migrations.AddField(
            model_name='leadv2',
            name='contact_id',
            field=models.UUIDField(blank=True, help_text='Related contact (UUID)', null=True),
        ),
        migrations.AddField(
            model_name='leadv2',
            name='created_by_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadv2',
            name='is_converted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='leadv2',
            name='rating',
            field=models.CharField(blank=True, choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], help_text='Lead quality rating', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leadv2',
            name='source',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('referral', 'Referral'), ('cold_call', 'Cold Call'), ('trade_show', 'Trade Show'), ('social_media', 'Social Media'), ('advertisement', 'Advertisement'), ('partner', 'Partner'), ('webinar', 'Webinar'), ('email_campaign', 'Email Campaign'), ('other', 'Other')], db_index=True, help_text='How the lead was acquired', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leadv2',
            name='updated_by_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leadv2',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='leadv2',
            name='owner_id',
            field=models.UUIDField(db_index=True, help_text='User who created this lead'),
        ),
        migrations.AlterField(
            model_name='leadv2',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('unqualified', 'Unqualified'), ('converted', 'Converted'), ('lost', 'Lost')], db_index=True, default='new', max_length=50),
        ),
        migrations.AddIndex(
            model_name='leadv2',
            index=models.Index(fields=['org_id', 'assigned_to_id', 'status'], name='leads_v2_my_leads_idx'),
        ),
        migrations.AddIndex(
            model_name='leadv2',
            index=models.Index(fields=['org_id', 'status', 'created_at'], name='leads_v2_status_idx'),
        ),
        migrations.AddIndex(
            model_name='leadv2',
            index=models.Index(fields=['org_id', 'is_converted'], name='leads_v2_conversion_idx'),
        ),
        migrations.AddIndex(
            model_name='leadv2',
            index=models.Index(fields=['org_id', 'source'], name='leads_v2_source_idx'),
        ),
    ]
