# Generated by Django 5.2.11 on 2026-03-02 10:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineV2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('owner_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pipeline V2',
                'verbose_name_plural': 'Pipelines V2',
                'db_table': 'crm_pipelines_v2',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['org_id', 'is_default'], name='pipelines_v2_default_idx'), models.Index(fields=['org_id', 'is_active'], name='pipelines_v2_active_idx'), models.Index(fields=['org_id', 'deleted_at'], name='pipelines_v2_deleted_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_default', True)), fields=('org_id',), name='unique_default_pipeline_v2_per_org')],
            },
        ),
        migrations.CreateModel(
            name='PipelineStageV2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('probability', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_won', models.BooleanField(default=False)),
                ('is_lost', models.BooleanField(default=False)),
                ('rotting_days', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.CharField(default='#6B7280', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='pipelines_v2.pipelinev2')),
            ],
            options={
                'verbose_name': 'Pipeline Stage V2',
                'verbose_name_plural': 'Pipeline Stages V2',
                'db_table': 'crm_pipeline_stages_v2',
                'ordering': ['pipeline', 'order'],
                'indexes': [models.Index(fields=['pipeline', 'order'], name='stages_v2_pipeline_order_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_won', True)), fields=('pipeline',), name='unique_won_stage_v2_per_pipeline'), models.UniqueConstraint(condition=models.Q(('is_lost', True)), fields=('pipeline',), name='unique_lost_stage_v2_per_pipeline'), models.CheckConstraint(condition=models.Q(('is_lost', True), ('is_won', True), _negated=True), name='stage_v2_not_both_won_and_lost')],
            },
        ),
    ]
