def get_default_lead_schema():
    """
    Get default lead form schema with industry-standard fields.
    
    Based on:
    - Salesforce Lead object
    - HubSpot Contact properties
    - Zoho CRM Leads module
    - V1 Lead model (for backward compatibility)
    
    Returns:
        dict: Complete form schema with sections and fields
    """
    return {
        'version': '1.0.0',
        'sections': [
            {
                'id': 'contact_info',
                'title': 'Contact Information',
                'description': 'Basic contact details',
                'columns': 2,
                'collapsible': False,
                'fields': [
                    {
                        'name': 'first_name',
                        'label': 'First Name',
                        'field_type': 'text',
                        'is_required': True,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'Enter first name',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'last_name',
                        'label': 'Last Name',
                        'field_type': 'text',
                        'is_required': True,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'Enter last name',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'email',
                        'label': 'Email',
                        'field_type': 'email',
                        'is_required': True,
                        'is_unique': True,
                        'is_searchable': True,
                        'placeholder': 'email@example.com',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'phone',
                        'label': 'Phone',
                        'field_type': 'phone',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': '+1 (555) 123-4567',
                        'help_text': 'Primary phone number',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'mobile',
                        'label': 'Mobile',
                        'field_type': 'phone',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': '+1 (555) 987-6543',
                        'help_text': 'Mobile phone number',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'website',
                        'label': 'Website',
                        'field_type': 'url',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'https://example.com',
                        'help_text': 'Company or personal website',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                ]
            },
            {
                'id': 'company_info',
                'title': 'Company Information',
                'columns': 2,
                'collapsible': False,
                'fields': [
                    {
                        'name': 'company',
                        'label': 'Company',
                        'field_type': 'lookup',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'Select or search company',
                        'help_text': 'Link to existing company record',
                        'validation_rules': {},
                        'options': {
                            'entity': 'company',
                            'api_endpoint': '/crm/api/v2/forms/definitions/lookup-options/?entity=company',
                            'display_field': 'label',
                            'value_field': 'id',
                            'searchable': True,
                            'allow_create': True,
                        },
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'company_name',
                        'label': 'Company Name',
                        'field_type': 'text',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'Company name',
                        'help_text': 'Company name (free text)',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'title',
                        'label': 'Job Title',
                        'field_type': 'text',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'e.g., Sales Manager',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'industry',
                        'label': 'Industry',
                        'field_type': 'select',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'Select industry',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {
                            'options': [
                                {'value': 'technology', 'label': 'Technology'},
                                {'value': 'finance', 'label': 'Finance & Banking'},
                                {'value': 'healthcare', 'label': 'Healthcare'},
                                {'value': 'retail', 'label': 'Retail & E-commerce'},
                                {'value': 'manufacturing', 'label': 'Manufacturing'},
                                {'value': 'real_estate', 'label': 'Real Estate'},
                                {'value': 'education', 'label': 'Education'},
                                {'value': 'consulting', 'label': 'Consulting'},
                                {'value': 'other', 'label': 'Other'},
                            ]
                        },
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'annual_revenue',
                        'label': 'Annual Revenue',
                        'field_type': 'currency',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': False,
                        'placeholder': '0.00',
                        'help_text': 'Company annual revenue',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'employees',
                        'label': 'Number of Employees',
                        'field_type': 'select',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': False,
                        'placeholder': 'Select size',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {
                            'options': [
                                {'value': '1', 'label': '1'},
                                {'value': '2-10', 'label': '2-10'},
                                {'value': '11-50', 'label': '11-50'},
                                {'value': '51-200', 'label': '51-200'},
                                {'value': '201-500', 'label': '201-500'},
                                {'value': '501-1000', 'label': '501-1000'},
                                {'value': '1000+', 'label': '1000+'},
                            ]
                        },
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                ]
            },
            {
                'id': 'address',
                'title': 'Address Information',
                'columns': 2,
                'collapsible': True,
                'fields': [
                    {
                        'name': 'address_line1',
                        'label': 'Street Address',
                        'field_type': 'text',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': '123 Main Street',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'full',
                        'readonly': False,
                    },
                    {
                        'name': 'city',
                        'label': 'City',
                        'field_type': 'text',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'San Francisco',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'state',
                        'label': 'State/Province',
                        'field_type': 'text',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'CA',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'postal_code',
                        'label': 'Zip/Postal Code',
                        'field_type': 'text',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': '94102',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'country',
                        'label': 'Country',
                        'field_type': 'text',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'United States',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                ]
            },
            {
                'id': 'qualification',
                'title': 'Lead Qualification',
                'columns': 2,
                'collapsible': False,
                'fields': [
                    {
                        'name': 'assigned_to',
                        'label': 'Assigned To',
                        'field_type': 'lookup',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'Select user',
                        'help_text': 'Sales rep responsible for this lead',
                        'validation_rules': {},
                        'options': {
                            'entity': 'user',
                            'api_endpoint': '/org/api/v1/orgs/__ORG_ID__/members?page_size=100&status=active',
                            'display_field': 'display_name',
                            'value_field': 'user_id',
                            'searchable': True,
                            'data_path': 'members',
                        },
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'status',
                        'label': 'Status',
                        'field_type': 'select',
                        'is_required': True,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': '',
                        'help_text': 'Current stage of lead',
                        'validation_rules': {},
                        'options': {
                            'options': [
                                {'value': 'new', 'label': 'New', 'color': '#3b82f6'},
                                {'value': 'contacted', 'label': 'Contacted', 'color': '#8b5cf6'},
                                {'value': 'qualified', 'label': 'Qualified', 'color': '#10b981'},
                                {'value': 'unqualified', 'label': 'Unqualified', 'color': '#ef4444'},
                                {'value': 'converted', 'label': 'Converted', 'color': '#22c55e'},
                            ]
                        },
                        'default_value': 'new',
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'source',
                        'label': 'Lead Source',
                        'field_type': 'select',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'Select source',
                        'help_text': 'How did we get this lead?',
                        'validation_rules': {},
                        'options': {
                            'options': [
                                {'value': 'website', 'label': 'Website'},
                                {'value': 'referral', 'label': 'Referral'},
                                {'value': 'cold_call', 'label': 'Cold Call'},
                                {'value': 'trade_show', 'label': 'Trade Show'},
                                {'value': 'social_media', 'label': 'Social Media'},
                                {'value': 'advertisement', 'label': 'Advertisement'},
                                {'value': 'partner', 'label': 'Partner'},
                                {'value': 'webinar', 'label': 'Webinar'},
                                {'value': 'email_campaign', 'label': 'Email Campaign'},
                                {'value': 'other', 'label': 'Other'},
                            ]
                        },
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'source_detail',
                        'label': 'Source Details',
                        'field_type': 'text',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'e.g., Google Ads Q1 Campaign',
                        'help_text': 'Specific campaign or referrer',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'rating',
                        'label': 'Lead Rating',
                        'field_type': 'select',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'Select rating',
                        'help_text': 'Priority level of this lead',
                        'validation_rules': {},
                        'options': {
                            'options': [
                                {'value': 'hot', 'label': 'Hot', 'color': '#ef4444'},
                                {'value': 'warm', 'label': 'Warm', 'color': '#f59e0b'},
                                {'value': 'cold', 'label': 'Cold', 'color': '#3b82f6'},
                            ]
                        },
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'lead_score',
                        'label': 'Lead Score',
                        'field_type': 'number',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': False,
                        'placeholder': '0-100',
                        'help_text': 'Calculated lead score (0-100)',
                        'validation_rules': {'min': 0, 'max': 100},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                ]
            },
            {
                'id': 'additional',
                'title': 'Additional Information',
                'columns': 1,
                'collapsible': True,
                'fields': [
                    {
                        'name': 'description',
                        'label': 'Notes',
                        'field_type': 'textarea',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'Add notes about this lead...',
                        'help_text': 'Any additional information about the lead',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'full',
                        'readonly': False,
                    },
                ]
            }
        ]
    }


def get_default_contact_schema():
    """
    Get default contact form schema with industry-standard fields.

    Based on V1 Contact model + Salesforce Contact / HubSpot Contact patterns.

    Contact-ONLY fields (NOT on Lead form):
      secondary_email, department, contact_type, lifecycle_stage,
      date_of_birth, preferred_language, linkedin_url, twitter_url,
      do_not_call, do_not_email

    Shared person fields (first_name, last_name, email, phone, mobile,
    company, title, address, assigned_to, status, source, description)
    are intentionally present on both -- every CRM (Salesforce, HubSpot,
    Zoho) does this because Lead and Contact are separate person entities.
    """
    return {
        'version': '1.0.0',
        'sections': [
            {
                'id': 'contact_info',
                'title': 'Contact Information',
                'description': 'Basic contact details',
                'columns': 2,
                'collapsible': False,
                'fields': [
                    {
                        'name': 'first_name',
                        'label': 'First Name',
                        'field_type': 'text',
                        'is_required': True,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'Enter first name',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'last_name',
                        'label': 'Last Name',
                        'field_type': 'text',
                        'is_required': True,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'Enter last name',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'email',
                        'label': 'Email',
                        'field_type': 'email',
                        'is_required': True,
                        'is_unique': True,
                        'is_searchable': True,
                        'placeholder': 'email@example.com',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'secondary_email',
                        'label': 'Secondary Email',
                        'field_type': 'email',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'alternate@example.com',
                        'help_text': 'Alternate email address',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'phone',
                        'label': 'Phone',
                        'field_type': 'phone',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': '+1 (555) 123-4567',
                        'help_text': 'Primary phone number',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'mobile',
                        'label': 'Mobile',
                        'field_type': 'phone',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': '+1 (555) 987-6543',
                        'help_text': 'Mobile phone number',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                ]
            },
            {
                'id': 'professional_info',
                'title': 'Professional Information',
                'columns': 2,
                'collapsible': False,
                'fields': [
                    {
                        'name': 'company',
                        'label': 'Company',
                        'field_type': 'lookup',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'Select or search company',
                        'help_text': 'Link to existing company record',
                        'validation_rules': {},
                        'options': {
                            'entity': 'company',
                            'api_endpoint': '/crm/api/v2/forms/definitions/lookup-options/?entity=company',
                            'display_field': 'label',
                            'value_field': 'id',
                            'searchable': True,
                            'allow_create': True,
                        },
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'title',
                        'label': 'Job Title',
                        'field_type': 'text',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'e.g., Sales Manager',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'department',
                        'label': 'Department',
                        'field_type': 'text',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'e.g., Marketing, Engineering',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                ]
            },
            {
                'id': 'lifecycle',
                'title': 'Lifecycle & Classification',
                'columns': 2,
                'collapsible': False,
                'fields': [
                    {
                        'name': 'assigned_to',
                        'label': 'Contact Owner',
                        'field_type': 'lookup',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'Select user',
                        'help_text': 'Account manager responsible for this contact',
                        'validation_rules': {},
                        'options': {
                            'entity': 'user',
                            'api_endpoint': '/org/api/v1/orgs/__ORG_ID__/members?page_size=100&status=active',
                            'display_field': 'display_name',
                            'value_field': 'user_id',
                            'searchable': True,
                            'data_path': 'members',
                        },
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'status',
                        'label': 'Status',
                        'field_type': 'select',
                        'is_required': True,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': '',
                        'help_text': 'Current contact status',
                        'validation_rules': {},
                        'options': {
                            'options': [
                                {'value': 'active', 'label': 'Active', 'color': '#10b981'},
                                {'value': 'inactive', 'label': 'Inactive', 'color': '#6b7280'},
                                {'value': 'bounced', 'label': 'Bounced', 'color': '#ef4444'},
                                {'value': 'unsubscribed', 'label': 'Unsubscribed', 'color': '#f59e0b'},
                                {'value': 'archived', 'label': 'Archived', 'color': '#8b5cf6'},
                            ]
                        },
                        'default_value': 'active',
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'source',
                        'label': 'Source',
                        'field_type': 'select',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'Select source',
                        'help_text': 'How did we acquire this contact?',
                        'validation_rules': {},
                        'options': {
                            'options': [
                                {'value': 'lead_conversion', 'label': 'Lead Conversion'},
                                {'value': 'website', 'label': 'Website'},
                                {'value': 'referral', 'label': 'Referral'},
                                {'value': 'cold_call', 'label': 'Cold Call'},
                                {'value': 'social_media', 'label': 'Social Media'},
                                {'value': 'trade_show', 'label': 'Trade Show'},
                                {'value': 'advertisement', 'label': 'Advertisement'},
                                {'value': 'partner', 'label': 'Partner'},
                                {'value': 'webinar', 'label': 'Webinar'},
                                {'value': 'email_campaign', 'label': 'Email Campaign'},
                                {'value': 'import', 'label': 'Data Import'},
                                {'value': 'other', 'label': 'Other'},
                            ]
                        },
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                ]
            },
            {
                'id': 'address',
                'title': 'Address Information',
                'columns': 2,
                'collapsible': True,
                'fields': [
                    {
                        'name': 'address_line1',
                        'label': 'Street Address',
                        'field_type': 'text',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': '123 Main Street',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'full',
                        'readonly': False,
                    },
                    {
                        'name': 'address_line2',
                        'label': 'Address Line 2',
                        'field_type': 'text',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': False,
                        'placeholder': 'Apt, Suite, Floor, etc.',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'full',
                        'readonly': False,
                    },
                    {
                        'name': 'city',
                        'label': 'City',
                        'field_type': 'text',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'San Francisco',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'state',
                        'label': 'State/Province',
                        'field_type': 'text',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'CA',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'postal_code',
                        'label': 'Zip/Postal Code',
                        'field_type': 'text',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': '94102',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'country',
                        'label': 'Country',
                        'field_type': 'text',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'United States',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                ]
            },
            {
                'id': 'social',
                'title': 'Social & Web',
                'columns': 2,
                'collapsible': True,
                'fields': [
                    {
                        'name': 'linkedin_url',
                        'label': 'LinkedIn',
                        'field_type': 'url',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': False,
                        'placeholder': 'https://linkedin.com/in/...',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'twitter_url',
                        'label': 'Twitter / X',
                        'field_type': 'url',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': False,
                        'placeholder': 'https://x.com/...',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                ]
            },
            {
                'id': 'communication',
                'title': 'Communication Preferences',
                'columns': 2,
                'collapsible': True,
                'fields': [
                    {
                        'name': 'do_not_call',
                        'label': 'Do Not Call',
                        'field_type': 'checkbox',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': False,
                        'placeholder': '',
                        'help_text': 'Contact has opted out of phone calls',
                        'validation_rules': {},
                        'options': {},
                        'default_value': False,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'do_not_email',
                        'label': 'Do Not Email',
                        'field_type': 'checkbox',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': False,
                        'placeholder': '',
                        'help_text': 'Contact has opted out of email',
                        'validation_rules': {},
                        'options': {},
                        'default_value': False,
                        'width': 'half',
                        'readonly': False,
                    },
                ]
            },
            {
                'id': 'additional',
                'title': 'Additional Information',
                'columns': 1,
                'collapsible': True,
                'fields': [
                    {
                        'name': 'description',
                        'label': 'Notes',
                        'field_type': 'textarea',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'Add notes about this contact...',
                        'help_text': 'Any additional information about the contact',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'full',
                        'readonly': False,
                    },
                ]
            }
        ]
    }


def get_default_company_schema():
    """
    Get default company form schema.

    Returns:
        dict: Complete form schema for companies
    """
    return {
        'version': '1.0.0',
        'sections': [
            {
                'id': 'company_details',
                'title': 'Company Details',
                'columns': 2,
                'collapsible': False,
                'fields': [
                    {
                        'name': 'name',
                        'label': 'Company Name',
                        'field_type': 'text',
                        'is_required': True,
                        'is_unique': True,
                        'is_searchable': True,
                        'placeholder': 'Enter company name',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'website',
                        'label': 'Website',
                        'field_type': 'url',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'https://example.com',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'email',
                        'label': 'Email',
                        'field_type': 'email',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'info@company.com',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'phone',
                        'label': 'Phone',
                        'field_type': 'phone',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': '+1 (555) 123-4567',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'industry',
                        'label': 'Industry',
                        'field_type': 'select',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'Select industry',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {
                            'options': [
                                {'value': 'technology', 'label': 'Technology'},
                                {'value': 'finance', 'label': 'Finance'},
                                {'value': 'healthcare', 'label': 'Healthcare'},
                                {'value': 'retail', 'label': 'Retail'},
                                {'value': 'manufacturing', 'label': 'Manufacturing'},
                                {'value': 'education', 'label': 'Education'},
                                {'value': 'real_estate', 'label': 'Real Estate'},
                                {'value': 'consulting', 'label': 'Consulting'},
                                {'value': 'media', 'label': 'Media & Entertainment'},
                                {'value': 'nonprofit', 'label': 'Non-Profit'},
                                {'value': 'other', 'label': 'Other'},
                            ]
                        },
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'size',
                        'label': 'Company Size',
                        'field_type': 'select',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'Select size',
                        'help_text': 'Number of employees',
                        'validation_rules': {},
                        'options': {
                            'options': [
                                {'value': '1', 'label': '1'},
                                {'value': '2-10', 'label': '2-10'},
                                {'value': '11-50', 'label': '11-50'},
                                {'value': '51-200', 'label': '51-200'},
                                {'value': '201-500', 'label': '201-500'},
                                {'value': '501-1000', 'label': '501-1000'},
                                {'value': '1000+', 'label': '1000+'},
                            ]
                        },
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                ]
            },
            {
                'id': 'financials',
                'title': 'Financial Details',
                'columns': 2,
                'collapsible': True,
                'fields': [
                    {
                        'name': 'annual_revenue',
                        'label': 'Annual Revenue',
                        'field_type': 'currency',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': False,
                        'placeholder': '0.00',
                        'help_text': 'Estimated annual revenue',
                        'validation_rules': {'min': 0},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'employee_count',
                        'label': 'Employee Count',
                        'field_type': 'number',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': False,
                        'placeholder': '0',
                        'help_text': 'Exact number of employees',
                        'validation_rules': {'min': 0},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                ]
            },
            {
                'id': 'address',
                'title': 'Address Information',
                'columns': 2,
                'collapsible': True,
                'fields': [
                    {
                        'name': 'address_line1',
                        'label': 'Street Address',
                        'field_type': 'text',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': '123 Main Street',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'full',
                        'readonly': False,
                    },
                    {
                        'name': 'address_line2',
                        'label': 'Address Line 2',
                        'field_type': 'text',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': False,
                        'placeholder': 'Suite, Floor, etc.',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'full',
                        'readonly': False,
                    },
                    {
                        'name': 'city',
                        'label': 'City',
                        'field_type': 'text',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'San Francisco',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'state',
                        'label': 'State/Province',
                        'field_type': 'text',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'CA',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'postal_code',
                        'label': 'Zip/Postal Code',
                        'field_type': 'text',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': '94102',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'country',
                        'label': 'Country',
                        'field_type': 'text',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'United States',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                ]
            },
            {
                'id': 'social',
                'title': 'Social & Web',
                'columns': 2,
                'collapsible': True,
                'fields': [
                    {
                        'name': 'linkedin_url',
                        'label': 'LinkedIn',
                        'field_type': 'url',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': False,
                        'placeholder': 'https://linkedin.com/company/...',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'twitter_url',
                        'label': 'Twitter / X',
                        'field_type': 'url',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': False,
                        'placeholder': 'https://x.com/...',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'facebook_url',
                        'label': 'Facebook',
                        'field_type': 'url',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': False,
                        'placeholder': 'https://facebook.com/...',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                ]
            },
            {
                'id': 'additional',
                'title': 'Additional Information',
                'columns': 1,
                'collapsible': True,
                'fields': [
                    {
                        'name': 'description',
                        'label': 'Description',
                        'field_type': 'textarea',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'Add notes about this company...',
                        'help_text': 'Any additional information about the company',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'full',
                        'readonly': False,
                    },
                ]
            }
        ]
    }


def _get_pipeline_stage_options():
    """Load stage options from the default PipelineV2, falling back to hardcoded defaults."""
    try:
        from pipelines_v2.models import PipelineV2
        pipeline = PipelineV2.objects.filter(
            is_default=True, deleted_at__isnull=True
        ).first()
        if not pipeline:
            pipeline = PipelineV2.objects.filter(
                deleted_at__isnull=True
            ).first()
        if pipeline:
            stages = pipeline.stages.all().order_by('order')
            if stages.exists():
                return [
                    {'value': s.name.lower().replace(' ', '_'), 'label': s.name, 'color': s.color}
                    for s in stages
                ], stages.first().name.lower().replace(' ', '_')
    except Exception:
        pass
    return [
        {'value': 'prospecting', 'label': 'Prospecting'},
        {'value': 'qualification', 'label': 'Qualification'},
        {'value': 'proposal', 'label': 'Proposal'},
        {'value': 'negotiation', 'label': 'Negotiation'},
        {'value': 'closed_won', 'label': 'Closed Won'},
        {'value': 'closed_lost', 'label': 'Closed Lost'},
    ], 'prospecting'


def get_default_deal_schema():
    """
    Get default deal form schema.

    Matches V1 Deal model fields. System fields (stage, value, currency,
    probability, expected_close_date, actual_close_date, loss_reason) are
    routed to DB columns by the serializer; the rest stay in entity_data.
    Stage options are loaded dynamically from PipelineV2.

    Returns:
        dict: Complete form schema for deals
    """
    stage_options, stage_default = _get_pipeline_stage_options()

    return {
        'version': '1.0.0',
        'sections': [
            {
                'id': 'deal_info',
                'title': 'Deal Information',
                'columns': 2,
                'collapsible': False,
                'fields': [
                    {
                        'name': 'name',
                        'label': 'Deal Name',
                        'field_type': 'text',
                        'is_required': True,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'Enter deal name',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'full',
                        'readonly': False,
                    },
                    {
                        'name': 'value',
                        'label': 'Deal Value',
                        'field_type': 'currency',
                        'is_required': True,
                        'is_unique': False,
                        'is_searchable': False,
                        'placeholder': '0.00',
                        'help_text': '',
                        'validation_rules': {'min': 0},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'currency',
                        'label': 'Currency',
                        'field_type': 'select',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': False,
                        'placeholder': 'Select currency',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {
                            'options': [
                                {'value': 'USD', 'label': 'USD'},
                                {'value': 'EUR', 'label': 'EUR'},
                                {'value': 'GBP', 'label': 'GBP'},
                                {'value': 'INR', 'label': 'INR'},
                                {'value': 'AED', 'label': 'AED'},
                                {'value': 'CAD', 'label': 'CAD'},
                                {'value': 'AUD', 'label': 'AUD'},
                            ]
                        },
                        'default_value': 'USD',
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'stage',
                        'label': 'Stage',
                        'field_type': 'select',
                        'is_required': True,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'Select stage',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {
                            'options': stage_options,
                        },
                        'default_value': stage_default,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'probability',
                        'label': 'Probability (%)',
                        'field_type': 'number',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': False,
                        'placeholder': '0-100',
                        'help_text': 'Win probability percentage',
                        'validation_rules': {'min': 0, 'max': 100},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'pipeline',
                        'label': 'Pipeline',
                        'field_type': 'lookup',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': False,
                        'placeholder': 'Select pipeline',
                        'help_text': 'Sales pipeline this deal belongs to',
                        'validation_rules': {},
                        'options': {
                            'entity': 'pipeline',
                            'api_endpoint': '/crm/api/v2/deals/pipelines/',
                            'display_field': 'name',
                            'value_field': 'id',
                            'data_path': 'pipelines',
                        },
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                ]
            },
            {
                'id': 'relationships',
                'title': 'Relationships',
                'columns': 2,
                'collapsible': False,
                'fields': [
                    {
                        'name': 'assigned_to',
                        'label': 'Deal Owner',
                        'field_type': 'lookup',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': False,
                        'placeholder': 'Select deal owner',
                        'help_text': 'Sales rep responsible for this deal',
                        'validation_rules': {},
                        'options': {
                            'entity': 'user',
                            'api_endpoint': '/org/api/v1/orgs/__ORG_ID__/members?page_size=100&status=active',
                            'display_field': 'display_name',
                            'value_field': 'user_id',
                            'searchable': True,
                            'data_path': 'members',
                        },
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'contact',
                        'label': 'Primary Contact',
                        'field_type': 'lookup',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': False,
                        'placeholder': 'Select primary contact',
                        'help_text': 'Main contact person for this deal',
                        'validation_rules': {},
                        'options': {
                            'entity': 'contact',
                            'api_endpoint': '/crm/api/v2/forms/definitions/lookup-options/?entity=contact',
                            'display_field': 'label',
                            'value_field': 'id',
                            'searchable': True,
                            'allow_create': True,
                        },
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'company',
                        'label': 'Company',
                        'field_type': 'lookup',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': False,
                        'placeholder': 'Select company',
                        'help_text': 'Company associated with this deal',
                        'validation_rules': {},
                        'options': {
                            'entity': 'company',
                            'api_endpoint': '/crm/api/v2/forms/definitions/lookup-options/?entity=company',
                            'display_field': 'label',
                            'value_field': 'id',
                            'searchable': True,
                            'allow_create': True,
                        },
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                ]
            },
            {
                'id': 'timeline',
                'title': 'Timeline',
                'columns': 2,
                'collapsible': False,
                'fields': [
                    {
                        'name': 'expected_close_date',
                        'label': 'Expected Close Date',
                        'field_type': 'date',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': False,
                        'placeholder': 'Select date',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'actual_close_date',
                        'label': 'Actual Close Date',
                        'field_type': 'date',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': False,
                        'placeholder': 'Select date',
                        'help_text': 'Set automatically when deal is won/lost',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                ]
            },
            {
                'id': 'loss_tracking',
                'title': 'Loss Details',
                'columns': 2,
                'collapsible': True,
                'fields': [
                    {
                        'name': 'loss_reason',
                        'label': 'Loss Reason',
                        'field_type': 'select',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'Select reason',
                        'help_text': 'Applicable when deal is lost',
                        'validation_rules': {},
                        'options': {
                            'options': [
                                {'value': 'price', 'label': 'Price Too High'},
                                {'value': 'competitor', 'label': 'Lost to Competitor'},
                                {'value': 'no_budget', 'label': 'No Budget'},
                                {'value': 'no_decision', 'label': 'No Decision Made'},
                                {'value': 'timing', 'label': 'Bad Timing'},
                                {'value': 'product_fit', 'label': 'Product Not a Fit'},
                                {'value': 'relationship', 'label': 'Relationship Issues'},
                                {'value': 'other', 'label': 'Other'},
                            ]
                        },
                        'default_value': None,
                        'width': 'half',
                        'readonly': False,
                    },
                    {
                        'name': 'loss_notes',
                        'label': 'Loss Notes',
                        'field_type': 'textarea',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': False,
                        'placeholder': 'Additional notes about why the deal was lost...',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'full',
                        'readonly': False,
                    },
                ]
            },
            {
                'id': 'description',
                'title': 'Description',
                'columns': 1,
                'collapsible': True,
                'fields': [
                    {
                        'name': 'description',
                        'label': 'Description',
                        'field_type': 'textarea',
                        'is_required': False,
                        'is_unique': False,
                        'is_searchable': True,
                        'placeholder': 'Deal description, notes, and context...',
                        'help_text': '',
                        'validation_rules': {},
                        'options': {},
                        'default_value': None,
                        'width': 'full',
                        'readonly': False,
                    },
                ]
            },
        ]
    }
