# Generated by Django 5.2.11 on 2026-02-26 06:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org_id', models.UUIDField(db_index=True)),
                ('entity_type', models.CharField(choices=[('contact', 'Contact'), ('company', 'Company'), ('deal', 'Deal'), ('lead', 'Lead')], db_index=True, max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('email', 'Email'), ('phone', 'Phone'), ('url', 'URL'), ('number', 'Number'), ('decimal', 'Decimal'), ('currency', 'Currency'), ('percentage', 'Percentage'), ('date', 'Date'), ('datetime', 'Date & Time'), ('time', 'Time'), ('select', 'Dropdown'), ('multi_select', 'Multi-Select'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkbox'), ('boolean', 'Yes/No')], max_length=50)),
                ('is_core', models.BooleanField(default=False)),
                ('is_required', models.BooleanField(default=False)),
                ('is_unique', models.BooleanField(default=False)),
                ('is_searchable', models.BooleanField(default=True)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('help_text', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crm_field_definitions',
                'indexes': [models.Index(fields=['org_id', 'entity_type', 'is_active'], name='crm_field_d_org_id_648ae5_idx'), models.Index(fields=['org_id', 'entity_type', 'is_searchable'], name='crm_field_d_org_id_bb0f7c_idx'), models.Index(fields=['org_id', 'entity_type', 'display_order'], name='crm_field_d_org_id_624c30_idx')],
                'unique_together': {('org_id', 'entity_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FormDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org_id', models.UUIDField(db_index=True)),
                ('entity_type', models.CharField(choices=[('contact', 'Contact'), ('company', 'Company'), ('deal', 'Deal'), ('lead', 'Lead')], db_index=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('form_type', models.CharField(choices=[('create', 'Create Form'), ('edit', 'Edit Form'), ('quick_add', 'Quick Add Form'), ('web_form', 'Web Form'), ('detail_view', 'Detail View')], default='create', max_length=50)),
                ('schema', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crm_form_definitions',
                'indexes': [models.Index(fields=['org_id', 'entity_type', 'is_active'], name='crm_form_de_org_id_8328a6_idx'), models.Index(fields=['org_id', 'entity_type', 'form_type', 'is_default'], name='crm_form_de_org_id_b3e3ad_idx')],
                'unique_together': {('org_id', 'entity_type', 'name')},
            },
        ),
    ]
