# Generated by Django 5.2.10 on 2026-03-03 06:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_v2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactCompanyV2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_associations', to='contacts_v2.contactv2')),
            ],
            options={
                'db_table': 'crm_contact_companies_v2',
                'indexes': [models.Index(fields=['contact', 'is_primary'], name='cc_v2_primary_idx'), models.Index(fields=['company_id'], name='cc_v2_company_idx')],
                'constraints': [models.UniqueConstraint(fields=('contact', 'company_id'), name='unique_contact_company_v2')],
            },
        ),
    ]
